version: '3'
services:
#mssql docker
  fixit-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - fixitnet

  fixit-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:FixIt=Server=fixit-sql,1433;Database=IB160309Docker;User=sa;Password=QWElkj132!;ConnectRetryCount=0;
    ports:
      - 5000:80
    networks:
      - fixitnet
    links:
      - fixit-sql
    depends_on:
      - fixit-sql
      
networks:
  fixitnet:
    driver: bridge